const games = [
  {
    id: "g1",
    title: "Minecraft",
    genre: "Sandbox",
    isOnline: true,
    platforms: ["PC", "PlayStation", "Xbox", "Mobile"],
    rating: 4.9,
  },
  {
    id: "g2",
    title: "Fortnite",
    genre: "Battle Royale",
    isOnline: true,
    platforms: ["PC", "PlayStation", "Xbox"],
    rating: 4.6,
  },
  {
    id: "g3",
    title: "GTA V",
    genre: "Action",
    isOnline: false,
    platforms: ["PC", "PlayStation", "Xbox"],
    rating: 4.8,
  },
  {
    id: "g4",
    title: "Roblox",
    genre: "Multiplayer",
    isOnline: true,
    platforms: ["PC", "Mobile"],
    rating: 4.4,
  },
  {
    id: "g5",
    title: "Among Us",
    genre: "Party",
    isOnline: true,
    platforms: ["PC", "Mobile"],
    rating: 4.1,
  },
  {
    id: "g6",
    title: "CS:GO",
    genre: "Shooter",
    isOnline: true,
    platforms: ["PC"],
    rating: 4.7,
  },
  {
    id: "g7",
    title: "Valorant",
    genre: "Shooter",
    isOnline: true,
    platforms: ["PC"],
    rating: 4.5,
  },
  {
    id: "g8",
    title: "League of Legends",
    genre: "MOBA",
    isOnline: true,
    platforms: ["PC"],
    rating: 4.6,
  },
  {
    id: "g9",
    title: "Dota 2",
    genre: "MOBA",
    isOnline: true,
    platforms: ["PC"],
    rating: 4.4,
  },
  {
    id: "g10",
    title: "Cyberpunk 2077",
    genre: "RPG",
    isOnline: false,
    platforms: ["PC", "PlayStation", "Xbox"],
    rating: 4.0,
  },
];

export default games;
